### ISSUE TITLE
Cannot add 2 fields of same type in a single form

### ISSUE THREAD

**Issue by ramit-seth** [sir-captainmorgan21/ng-bootstrap-input#1]
If I try to add 2 fields of same type in a single form. Their validation work together. If one goes invalid, other turns red as well.

Sample code - 

> public currencyConfig: BootstrapInputConfigInterface = {
        type: 'currency',
        form: this.form,
        required: true,
        validationRegex: null,
        maskArray: null,
        maxLength: null
    };
 public newInputConfig: BootstrapInputConfigInterface = {
        type: 'currency',
        form: this.form,
        required: true,
        validationRegex: null,
        maskArray: null,
        maxLength: null
    };`

`<label>Currency</label>
<bootstrap-input [inputConfig]="currencyConfig"></bootstrap-input>
<label>Something else</label>
<bootstrap-input [inputConfig]="newInputConfig"></bootstrap-input>` 

please help

**Comment by sir-captainmorgan21** [comment]
@ramit-seth I will add a feature to enable passing in the form control name

**Comment by sir-captainmorgan21** [comment]
@ramit-seth I have completely re-engineered the library using angular cli's library builder. The consumption of the library has also changed. I am working on the README, but for now, use the github pages for examples. https://sir-captainmorgan21.github.io/ng-bootstrap-input/

npm package: ng-bootstrap-input@2.0.1

**Comment by sir-captainmorgan21** [comment]
I am going to close this issue. With the new inputs, you can now specify the form control's name, resolving the issue you were having.
